# Generated by Django 2.0.7 on 2018-07-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180718_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='views_total',
        ),
        migrations.AddField(
            model_name='posts',
            name='likes_total',
            field=models.IntegerField(default=0),
        ),
    ]
