# Generated by Django 2.0.7 on 2018-07-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180718_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='icon',
        ),
    ]
